/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import java.awt.CardLayout;
import javax.swing.JToggleButton;

/**
 *
 * @author potatos
 */
public class AddProduitJDialog extends javax.swing.JDialog {
    
    
    private Object[] produitsObjs;

    /**
     * Creates new form ProduitsJDialog
     */
    public AddProduitJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public Object[] showDialog(){
        this.setVisible(true);
        return produitsObjs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromageCharcuterieFruitAutreButtonGroup = new javax.swing.ButtonGroup();
        mainProduitsJPanel = new javax.swing.JPanel();
        fromageProduitsJToggleButton = new javax.swing.JToggleButton();
        charcuterieProduitsJToggleButton = new javax.swing.JToggleButton();
        fruitProduitsJToggleButton = new javax.swing.JToggleButton();
        autreProduitsJToggleButton = new javax.swing.JToggleButton();
        centreProduitsJPanel = new javax.swing.JPanel();
        fromageCardLayoutJPanel = new javax.swing.JPanel();
        nomFromageJLabel = new javax.swing.JLabel();
        nomFromageJTextField = new javax.swing.JTextField();
        quantitePersonneFromageJLabel = new javax.swing.JLabel();
        quantitePersonneFromageJTextField = new javax.swing.JTextField();
        uniteFromageJLabel = new javax.swing.JLabel();
        uniteFromageJComboBox = new javax.swing.JComboBox<>();
        prixUnitaireFromageJLabel = new javax.swing.JLabel();
        prixUnitaireFromageJTextField = new javax.swing.JTextField();
        charcuterieCardLayoutJPanel = new javax.swing.JPanel();
        nomCharcuterieJLabel = new javax.swing.JLabel();
        nomCharcuterieJTextField = new javax.swing.JTextField();
        quantitePersonneCharcuterieJLabel = new javax.swing.JLabel();
        quantitePersonneCharcuterieJTextField = new javax.swing.JTextField();
        uniteCharcuterieJLabel = new javax.swing.JLabel();
        uniteCharcuterieJComboBox = new javax.swing.JComboBox<>();
        prixUnitaireCharcuterieJLabel = new javax.swing.JLabel();
        prixUnitaireCharcuterieJTextField = new javax.swing.JTextField();
        FruitCardLayoutJPanel = new javax.swing.JPanel();
        nomFruitJLabel = new javax.swing.JLabel();
        nomFruitJTextField = new javax.swing.JTextField();
        quantitePersonneFruitJLabel = new javax.swing.JLabel();
        quantitePersonneFruitJTextField = new javax.swing.JTextField();
        uniteFruitJLabel = new javax.swing.JLabel();
        uniteFruitJComboBox = new javax.swing.JComboBox<>();
        autreFruitJLabel = new javax.swing.JLabel();
        autreFruitJTextField = new javax.swing.JTextField();
        autreCardLayoutJPanel = new javax.swing.JPanel();
        nomAutreJLabel = new javax.swing.JLabel();
        nomAutreJTextField = new javax.swing.JTextField();
        prixUnitaireAutreJLabel = new javax.swing.JLabel();
        prixUnitaireAutreJTextField = new javax.swing.JTextField();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        enregistrerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 20));

        fromageCharcuterieFruitAutreButtonGroup.add(fromageProduitsJToggleButton);
        fromageProduitsJToggleButton.setSelected(true);
        fromageProduitsJToggleButton.setText("Fromage");
        fromageProduitsJToggleButton.setMinimumSize(new java.awt.Dimension(100, 30));
        fromageProduitsJToggleButton.setPreferredSize(new java.awt.Dimension(100, 30));
        fromageProduitsJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyProduitsJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(fromageProduitsJToggleButton);

        fromageCharcuterieFruitAutreButtonGroup.add(charcuterieProduitsJToggleButton);
        charcuterieProduitsJToggleButton.setText("Charcuterie");
        charcuterieProduitsJToggleButton.setMinimumSize(new java.awt.Dimension(100, 30));
        charcuterieProduitsJToggleButton.setPreferredSize(new java.awt.Dimension(100, 30));
        charcuterieProduitsJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyProduitsJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(charcuterieProduitsJToggleButton);

        fromageCharcuterieFruitAutreButtonGroup.add(fruitProduitsJToggleButton);
        fruitProduitsJToggleButton.setText("Fruit");
        fruitProduitsJToggleButton.setMinimumSize(new java.awt.Dimension(100, 30));
        fruitProduitsJToggleButton.setPreferredSize(new java.awt.Dimension(100, 30));
        fruitProduitsJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyProduitsJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(fruitProduitsJToggleButton);

        fromageCharcuterieFruitAutreButtonGroup.add(autreProduitsJToggleButton);
        autreProduitsJToggleButton.setText("Autre");
        autreProduitsJToggleButton.setMinimumSize(new java.awt.Dimension(100, 30));
        autreProduitsJToggleButton.setPreferredSize(new java.awt.Dimension(100, 30));
        autreProduitsJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyProduitsJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(autreProduitsJToggleButton);

        getContentPane().add(mainProduitsJPanel, java.awt.BorderLayout.PAGE_START);

        centreProduitsJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centreProduitsJPanel.setLayout(new java.awt.CardLayout());

        fromageCardLayoutJPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        nomFromageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomFromageJLabel.setText("Nom du fromage");
        fromageCardLayoutJPanel.add(nomFromageJLabel);

        nomFromageJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fromageCardLayoutJPanel.add(nomFromageJTextField);

        quantitePersonneFromageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantitePersonneFromageJLabel.setText("Quantité par personne");
        fromageCardLayoutJPanel.add(quantitePersonneFromageJLabel);

        quantitePersonneFromageJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fromageCardLayoutJPanel.add(quantitePersonneFromageJTextField);

        uniteFromageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uniteFromageJLabel.setText("Unité");
        fromageCardLayoutJPanel.add(uniteFromageJLabel);

        uniteFromageJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAMME", "PIECE", "INDEFINIE" }));
        uniteFromageJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniteFromageJComboBoxActionPerformed(evt);
            }
        });
        fromageCardLayoutJPanel.add(uniteFromageJComboBox);

        prixUnitaireFromageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireFromageJLabel.setText("Prix unitaire ( Euro )");
        fromageCardLayoutJPanel.add(prixUnitaireFromageJLabel);

        prixUnitaireFromageJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fromageCardLayoutJPanel.add(prixUnitaireFromageJTextField);

        centreProduitsJPanel.add(fromageCardLayoutJPanel, "Fromage");

        charcuterieCardLayoutJPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        nomCharcuterieJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomCharcuterieJLabel.setText("Nom de la charcuterie");
        charcuterieCardLayoutJPanel.add(nomCharcuterieJLabel);

        nomCharcuterieJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        charcuterieCardLayoutJPanel.add(nomCharcuterieJTextField);

        quantitePersonneCharcuterieJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantitePersonneCharcuterieJLabel.setText("Quantité par personne");
        charcuterieCardLayoutJPanel.add(quantitePersonneCharcuterieJLabel);

        quantitePersonneCharcuterieJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        charcuterieCardLayoutJPanel.add(quantitePersonneCharcuterieJTextField);

        uniteCharcuterieJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uniteCharcuterieJLabel.setText("Unité");
        charcuterieCardLayoutJPanel.add(uniteCharcuterieJLabel);

        uniteCharcuterieJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAMME", "PIECE", "INDEFINIE" }));
        uniteCharcuterieJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniteCharcuterieJComboBoxActionPerformed(evt);
            }
        });
        charcuterieCardLayoutJPanel.add(uniteCharcuterieJComboBox);

        prixUnitaireCharcuterieJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireCharcuterieJLabel.setText("Prix unitaire ( Euro )");
        charcuterieCardLayoutJPanel.add(prixUnitaireCharcuterieJLabel);

        prixUnitaireCharcuterieJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        charcuterieCardLayoutJPanel.add(prixUnitaireCharcuterieJTextField);

        centreProduitsJPanel.add(charcuterieCardLayoutJPanel, "Charcuterie");

        FruitCardLayoutJPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        nomFruitJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomFruitJLabel.setText("Nom du fruit");
        FruitCardLayoutJPanel.add(nomFruitJLabel);

        nomFruitJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FruitCardLayoutJPanel.add(nomFruitJTextField);

        quantitePersonneFruitJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantitePersonneFruitJLabel.setText("Quantité par personne");
        FruitCardLayoutJPanel.add(quantitePersonneFruitJLabel);

        quantitePersonneFruitJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FruitCardLayoutJPanel.add(quantitePersonneFruitJTextField);

        uniteFruitJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uniteFruitJLabel.setText("Unité");
        FruitCardLayoutJPanel.add(uniteFruitJLabel);

        uniteFruitJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRAMME", "PIECE", "INDEFINIE" }));
        FruitCardLayoutJPanel.add(uniteFruitJComboBox);

        autreFruitJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autreFruitJLabel.setText("Prix unitaire ( Euro )");
        FruitCardLayoutJPanel.add(autreFruitJLabel);

        autreFruitJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FruitCardLayoutJPanel.add(autreFruitJTextField);

        centreProduitsJPanel.add(FruitCardLayoutJPanel, "Fruit");

        autreCardLayoutJPanel.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        nomAutreJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomAutreJLabel.setText("Nom du nouvel élément");
        autreCardLayoutJPanel.add(nomAutreJLabel);

        nomAutreJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        autreCardLayoutJPanel.add(nomAutreJTextField);

        prixUnitaireAutreJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireAutreJLabel.setText("Prix unitaire ( Euro )");
        autreCardLayoutJPanel.add(prixUnitaireAutreJLabel);

        prixUnitaireAutreJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        autreCardLayoutJPanel.add(prixUnitaireAutreJTextField);

        centreProduitsJPanel.add(autreCardLayoutJPanel, "Autre");

        getContentPane().add(centreProduitsJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        enregistrerJButton.setText("Enregistrer");
        enregistrerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(enregistrerJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void everyProduitsJToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_everyProduitsJToggleButtonActionPerformed
        // TODO add your handling code here:
        JToggleButton button = (JToggleButton) evt.getSource();
        String str = button.getText();
        
        CardLayout cardLayout = (CardLayout) centreProduitsJPanel.getLayout();
        cardLayout.show(centreProduitsJPanel, str);
    }//GEN-LAST:event_everyProduitsJToggleButtonActionPerformed

    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed

    private void enregistrerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerJButtonActionPerformed
        int type = 0;
        if(fromageProduitsJToggleButton.isSelected()){
            type = 0;
            this.produitsObjs = new Object[]{type, nomFromageJTextField.getText(), quantitePersonneFromageJTextField.getText(), uniteFromageJComboBox.getSelectedItem(), prixUnitaireFromageJTextField.getText()};
        } else if(charcuterieProduitsJToggleButton.isSelected()) {
            type = 1;
            this.produitsObjs = new Object[]{type, nomCharcuterieJTextField.getText(), quantitePersonneCharcuterieJTextField.getText(), uniteCharcuterieJComboBox.getSelectedItem(), prixUnitaireCharcuterieJTextField.getText()};
        } else if(fruitProduitsJToggleButton.isSelected()) {
            type = 2;
            this.produitsObjs = new Object[]{type, nomFruitJTextField.getText(), quantitePersonneFruitJTextField.getText(), uniteFruitJComboBox.getSelectedItem(), autreFruitJTextField.getText()};
        } else if(autreProduitsJToggleButton.isSelected()) {
            type = 3;
            this.produitsObjs = new Object[]{type, nomAutreJTextField.getText(), prixUnitaireAutreJTextField.getText()};
            System.out.println(prixUnitaireAutreJTextField.getText());
        }
        
        this.dispose();
    }//GEN-LAST:event_enregistrerJButtonActionPerformed

    private void uniteFromageJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniteFromageJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniteFromageJComboBoxActionPerformed

    private void uniteCharcuterieJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniteCharcuterieJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniteCharcuterieJComboBoxActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FruitCardLayoutJPanel;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel autreCardLayoutJPanel;
    private javax.swing.JLabel autreFruitJLabel;
    private javax.swing.JTextField autreFruitJTextField;
    private javax.swing.JToggleButton autreProduitsJToggleButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centreProduitsJPanel;
    private javax.swing.JPanel charcuterieCardLayoutJPanel;
    private javax.swing.JToggleButton charcuterieProduitsJToggleButton;
    private javax.swing.JButton enregistrerJButton;
    private javax.swing.JPanel fromageCardLayoutJPanel;
    private javax.swing.ButtonGroup fromageCharcuterieFruitAutreButtonGroup;
    private javax.swing.JToggleButton fromageProduitsJToggleButton;
    private javax.swing.JToggleButton fruitProduitsJToggleButton;
    private javax.swing.JPanel mainProduitsJPanel;
    private javax.swing.JLabel nomAutreJLabel;
    private javax.swing.JTextField nomAutreJTextField;
    private javax.swing.JLabel nomCharcuterieJLabel;
    private javax.swing.JTextField nomCharcuterieJTextField;
    private javax.swing.JLabel nomFromageJLabel;
    private javax.swing.JTextField nomFromageJTextField;
    private javax.swing.JLabel nomFruitJLabel;
    private javax.swing.JTextField nomFruitJTextField;
    private javax.swing.JLabel prixUnitaireAutreJLabel;
    private javax.swing.JTextField prixUnitaireAutreJTextField;
    private javax.swing.JLabel prixUnitaireCharcuterieJLabel;
    private javax.swing.JTextField prixUnitaireCharcuterieJTextField;
    private javax.swing.JLabel prixUnitaireFromageJLabel;
    private javax.swing.JTextField prixUnitaireFromageJTextField;
    private javax.swing.JLabel quantitePersonneCharcuterieJLabel;
    private javax.swing.JTextField quantitePersonneCharcuterieJTextField;
    private javax.swing.JLabel quantitePersonneFromageJLabel;
    private javax.swing.JTextField quantitePersonneFromageJTextField;
    private javax.swing.JLabel quantitePersonneFruitJLabel;
    private javax.swing.JTextField quantitePersonneFruitJTextField;
    private javax.swing.JComboBox<String> uniteCharcuterieJComboBox;
    private javax.swing.JLabel uniteCharcuterieJLabel;
    private javax.swing.JComboBox<String> uniteFromageJComboBox;
    private javax.swing.JLabel uniteFromageJLabel;
    private javax.swing.JComboBox<String> uniteFruitJComboBox;
    private javax.swing.JLabel uniteFruitJLabel;
    // End of variables declaration//GEN-END:variables
}
