/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.IApp;
import Model.Produits.Produit;
import java.util.ArrayList;

/**
 *
 * @author Léa Berne
 */
public class AddPlateauJDialog extends javax.swing.JDialog {
    private IApp iApp;
    private Object[] plateauObjs;
    private ArrayList produitsDuPlateau;
    /**
     * Creates new form PlateauxJDialog
     */
    public AddPlateauJDialog(java.awt.Frame parent, boolean modal, IApp iApp) {
        super(parent, modal);
        this.iApp = iApp;
        initComponents();
        this.produitsDuPlateau = new ArrayList<Produit>();
    }
    
    
    public Object[] showDialog(){
        this.setVisible(true);
        return this.plateauObjs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPlateauxJPanel = new javax.swing.JPanel();
        creationPlateauJLabel = new javax.swing.JLabel();
        centrePlateauxJPanel = new javax.swing.JPanel();
        prixUnitaireJLabel1 = new javax.swing.JLabel();
        prixUnitaireJTextField1 = new javax.swing.JTextField();
        nomPlateauJLabel1 = new javax.swing.JLabel();
        nomPlateauJTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        deleteProduitJButton = new javax.swing.JButton();
        viewProduitJButton = new javax.swing.JButton();
        addProduitJButton = new javax.swing.JButton();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        enregistrerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        creationPlateauJLabel.setText("Création des plateaux standards");
        mainPlateauxJPanel.add(creationPlateauJLabel);

        getContentPane().add(mainPlateauxJPanel, java.awt.BorderLayout.PAGE_START);

        centrePlateauxJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centrePlateauxJPanel.setLayout(new java.awt.GridBagLayout());

        prixUnitaireJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireJLabel1.setText("Prix unitaire ( Euro / Personne )");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        centrePlateauxJPanel.add(prixUnitaireJLabel1, gridBagConstraints);

        prixUnitaireJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixUnitaireJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixUnitaireJTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        centrePlateauxJPanel.add(prixUnitaireJTextField1, gridBagConstraints);

        nomPlateauJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomPlateauJLabel1.setText("Nom du plateau");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        centrePlateauxJPanel.add(nomPlateauJLabel1, gridBagConstraints);

        nomPlateauJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomPlateauJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPlateauJTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        centrePlateauxJPanel.add(nomPlateauJTextField1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        deleteProduitJButton.setText("Supprimer un produit");
        deleteProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteProduitJButton);

        viewProduitJButton.setText("Voir les produits");
        viewProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewProduitJButton);

        addProduitJButton.setText("Ajouter un produit");
        addProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addProduitJButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        centrePlateauxJPanel.add(jPanel2, gridBagConstraints);

        getContentPane().add(centrePlateauxJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        enregistrerJButton.setText("Enregistrer");
        enregistrerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(enregistrerJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed

    private void addProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduitJButtonActionPerformed
        AjoutProduitsPlateauxJDialog ajoutProduits = new AjoutProduitsPlateauxJDialog(null, true, this.iApp );
        Produit produit = ajoutProduits.showDialog();//type, nom, quantite, fruit, prix ou type, nom, prix si autre
        produitsDuPlateau.add(produit);
    }//GEN-LAST:event_addProduitJButtonActionPerformed

    private void viewProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProduitJButtonActionPerformed
        ViewProduitsPlateauJDialog newVoirPlateaux = new ViewProduitsPlateauJDialog(null, true, produitsDuPlateau);
        newVoirPlateaux.setVisible(true);
    }//GEN-LAST:event_viewProduitJButtonActionPerformed

    private void deleteProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduitJButtonActionPerformed
        DeleteProduitsPlateauJDialog1 deletePlateau = new DeleteProduitsPlateauJDialog1(null, true, iApp, this.produitsDuPlateau);
        this.produitsDuPlateau = deletePlateau.showDialog();
    }//GEN-LAST:event_deleteProduitJButtonActionPerformed

    private void nomPlateauJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPlateauJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomPlateauJTextField1ActionPerformed

    private void prixUnitaireJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixUnitaireJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireJTextField1ActionPerformed

    private void enregistrerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerJButtonActionPerformed
        this.plateauObjs = new Object[]{nomPlateauJTextField1.getText(), prixUnitaireJTextField1.getText(), produitsDuPlateau};
        this.dispose();
    }//GEN-LAST:event_enregistrerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduitJButton;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centrePlateauxJPanel;
    private javax.swing.JLabel creationPlateauJLabel;
    private javax.swing.JButton deleteProduitJButton;
    private javax.swing.JButton enregistrerJButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPlateauxJPanel;
    private javax.swing.JLabel nomPlateauJLabel1;
    private javax.swing.JTextField nomPlateauJTextField1;
    private javax.swing.JLabel prixUnitaireJLabel1;
    private javax.swing.JTextField prixUnitaireJTextField1;
    private javax.swing.JButton viewProduitJButton;
    // End of variables declaration//GEN-END:variables
}
