/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.Exceptions.ErreurInconnueException;
import Controller.Exceptions.NomTropLongException;
import Controller.Exceptions.PrixInvalideException;
import Controller.Exceptions.QuantiteParPersonneInvalideException;
import Controller.IApp;
import Model.Plateaux.Plateau;
import Model.Plateaux.PlateauPerso;
import Model.Produits.Produit;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author potatos
 */
public class AjoutPlateauCommandeJDialog extends javax.swing.JDialog {

    private ArrayList<Plateau> plateauxStandards;
    private DefaultComboBoxModel<String> plateauStandardComboBoxModel;
    private ArrayList produitsDuPlateau;
    private Object[] plateauDeLaCommandesObjs;
    private final IApp iApp;
        
    /**
     * Creates new form CommandesJDialog
     */
    public AjoutPlateauCommandeJDialog(java.awt.Frame parent, boolean modal, IApp iApp) {
        super(parent, modal);
        this.iApp = iApp;
        this.plateauStandardComboBoxModel = new DefaultComboBoxModel<String>();
        this.plateauxStandards = iApp.toutRecupererPlateauStandard();
        this.produitsDuPlateau = new ArrayList();
        for (Plateau plateau : plateauxStandards) {
            plateauStandardComboBoxModel.addElement(plateau.getNomPlateau());
        }
        initComponents(); 
    }
    
    
    public Object[] showDialog() {
        this.setVisible(true);
        return plateauDeLaCommandesObjs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        plateauxStandardsPersonnalisesButtonGroup = new javax.swing.ButtonGroup();
        mainProduitsJPanel = new javax.swing.JPanel();
        plateauxStandardJToggleButton = new javax.swing.JToggleButton();
        plateauxPersonnalisesJToggleButton = new javax.swing.JToggleButton();
        centreCommandesJPanel = new javax.swing.JPanel();
        plateauxStandardsInformationJPanel = new javax.swing.JPanel();
        choosePlateauStandardCommandeJLabel = new javax.swing.JLabel();
        choosePlateauStandardCommande = new javax.swing.JComboBox<>();
        nbPersonnesPlateauStandardJLabel = new javax.swing.JLabel();
        nbPersonnesPlateauStandardJTextField3 = new javax.swing.JTextField();
        quantitePlateauStandardJLabel1 = new javax.swing.JLabel();
        quantitePlateauStandardJTextField4 = new javax.swing.JTextField();
        plateauxPersonnalisesInformationJPanel = new javax.swing.JPanel();
        prixUnitaireJLabel2 = new javax.swing.JLabel();
        prixUnitaireJTextField2 = new javax.swing.JTextField();
        nomPlateauJLabel2 = new javax.swing.JLabel();
        nomPlateauJTextField2 = new javax.swing.JTextField();
        nbPersonnesPlateauPersoJLabel = new javax.swing.JLabel();
        nbPersonnesPlateauPersoJTextField = new javax.swing.JTextField();
        quantitePlateauPersoJLabel = new javax.swing.JLabel();
        quantitePlateauPersoJTextField = new javax.swing.JTextField();
        createFromPlateauStandard = new javax.swing.JButton();
        crudProduitPlateauPersoJPanel = new javax.swing.JPanel();
        deleteProduitJButton1 = new javax.swing.JButton();
        viewProduitJButton1 = new javax.swing.JButton();
        addProduitJButton1 = new javax.swing.JButton();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        enregistrerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        plateauxStandardsPersonnalisesButtonGroup.add(plateauxStandardJToggleButton);
        plateauxStandardJToggleButton.setSelected(true);
        plateauxStandardJToggleButton.setText("Plateaux Standards");
        plateauxStandardJToggleButton.setMinimumSize(new java.awt.Dimension(180, 30));
        plateauxStandardJToggleButton.setPreferredSize(new java.awt.Dimension(180, 30));
        plateauxStandardJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyPlateauxJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(plateauxStandardJToggleButton);

        plateauxStandardsPersonnalisesButtonGroup.add(plateauxPersonnalisesJToggleButton);
        plateauxPersonnalisesJToggleButton.setText("Plateaux Personnalisés");
        plateauxPersonnalisesJToggleButton.setMinimumSize(new java.awt.Dimension(180, 30));
        plateauxPersonnalisesJToggleButton.setPreferredSize(new java.awt.Dimension(180, 30));
        plateauxPersonnalisesJToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everyPlateauxJToggleButtonActionPerformed(evt);
            }
        });
        mainProduitsJPanel.add(plateauxPersonnalisesJToggleButton);

        getContentPane().add(mainProduitsJPanel, java.awt.BorderLayout.PAGE_START);

        centreCommandesJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centreCommandesJPanel.setLayout(new java.awt.CardLayout());

        plateauxStandardsInformationJPanel.setLayout(new java.awt.GridLayout(3, 2));

        choosePlateauStandardCommandeJLabel.setText("Choissisez le plateau désiré :");
        plateauxStandardsInformationJPanel.add(choosePlateauStandardCommandeJLabel);

        choosePlateauStandardCommande.setModel(plateauStandardComboBoxModel);
        choosePlateauStandardCommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePlateauStandardCommandeActionPerformed(evt);
            }
        });
        plateauxStandardsInformationJPanel.add(choosePlateauStandardCommande);

        nbPersonnesPlateauStandardJLabel.setText("Indiquez le nombre de personnes :");
        plateauxStandardsInformationJPanel.add(nbPersonnesPlateauStandardJLabel);

        nbPersonnesPlateauStandardJTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nbPersonnesPlateauStandardJTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbPersonnesPlateauStandardJTextField3ActionPerformed(evt);
            }
        });
        plateauxStandardsInformationJPanel.add(nbPersonnesPlateauStandardJTextField3);

        quantitePlateauStandardJLabel1.setText("Indiquez la quantité :");
        plateauxStandardsInformationJPanel.add(quantitePlateauStandardJLabel1);

        quantitePlateauStandardJTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantitePlateauStandardJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitePlateauStandardJTextField4ActionPerformed(evt);
            }
        });
        plateauxStandardsInformationJPanel.add(quantitePlateauStandardJTextField4);

        centreCommandesJPanel.add(plateauxStandardsInformationJPanel, "Plateaux Standards");

        plateauxPersonnalisesInformationJPanel.setLayout(new java.awt.GridBagLayout());

        prixUnitaireJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireJLabel2.setText("Prix unitaire ( Euro / Personne )");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        plateauxPersonnalisesInformationJPanel.add(prixUnitaireJLabel2, gridBagConstraints);

        prixUnitaireJTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixUnitaireJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixUnitaireJTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        plateauxPersonnalisesInformationJPanel.add(prixUnitaireJTextField2, gridBagConstraints);

        nomPlateauJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomPlateauJLabel2.setText("Nom du plateau");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        plateauxPersonnalisesInformationJPanel.add(nomPlateauJLabel2, gridBagConstraints);

        nomPlateauJTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomPlateauJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPlateauJTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        plateauxPersonnalisesInformationJPanel.add(nomPlateauJTextField2, gridBagConstraints);

        nbPersonnesPlateauPersoJLabel.setText("Indiquez le nombre de personnes :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        plateauxPersonnalisesInformationJPanel.add(nbPersonnesPlateauPersoJLabel, gridBagConstraints);

        nbPersonnesPlateauPersoJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nbPersonnesPlateauPersoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbPersonnesPlateauPersoJTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        plateauxPersonnalisesInformationJPanel.add(nbPersonnesPlateauPersoJTextField, gridBagConstraints);

        quantitePlateauPersoJLabel.setText("Indiquez la quantité :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        plateauxPersonnalisesInformationJPanel.add(quantitePlateauPersoJLabel, gridBagConstraints);

        quantitePlateauPersoJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantitePlateauPersoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitePlateauPersoJTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        plateauxPersonnalisesInformationJPanel.add(quantitePlateauPersoJTextField, gridBagConstraints);

        createFromPlateauStandard.setText("Créer à partir d'un plateau standard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        plateauxPersonnalisesInformationJPanel.add(createFromPlateauStandard, gridBagConstraints);

        crudProduitPlateauPersoJPanel.setLayout(new java.awt.GridLayout(1, 0));

        deleteProduitJButton1.setText("Supprimer un produit");
        deleteProduitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduitJButton1ActionPerformed(evt);
            }
        });
        crudProduitPlateauPersoJPanel.add(deleteProduitJButton1);

        viewProduitJButton1.setText("Voir les produits");
        viewProduitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProduitJButton1ActionPerformed(evt);
            }
        });
        crudProduitPlateauPersoJPanel.add(viewProduitJButton1);

        addProduitJButton1.setText("Ajouter un produit");
        addProduitJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduitJButton1ActionPerformed(evt);
            }
        });
        crudProduitPlateauPersoJPanel.add(addProduitJButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        plateauxPersonnalisesInformationJPanel.add(crudProduitPlateauPersoJPanel, gridBagConstraints);

        centreCommandesJPanel.add(plateauxPersonnalisesInformationJPanel, "Plateaux Personnalisés");

        getContentPane().add(centreCommandesJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        enregistrerJButton.setText("Enregistrer");
        enregistrerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(enregistrerJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed

    private void everyPlateauxJToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_everyPlateauxJToggleButtonActionPerformed
        JToggleButton button = (JToggleButton) evt.getSource();
        String str = button.getText();
        
        CardLayout cardLayout = (CardLayout) centreCommandesJPanel.getLayout();
        cardLayout.show(centreCommandesJPanel, str);
    }//GEN-LAST:event_everyPlateauxJToggleButtonActionPerformed

    private void prixUnitaireJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixUnitaireJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireJTextField2ActionPerformed

    private void nomPlateauJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPlateauJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomPlateauJTextField2ActionPerformed

    private void addProduitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduitJButton1ActionPerformed
        AjoutProduitsPlateauxJDialog ajoutProduits = new AjoutProduitsPlateauxJDialog(null, true, iApp);
        Produit produit = ajoutProduits.showDialog();
        produitsDuPlateau.add(produit);
    }//GEN-LAST:event_addProduitJButton1ActionPerformed

    private void viewProduitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProduitJButton1ActionPerformed
        ViewProduitsPlateauJDialog newVoirPlateaux = new ViewProduitsPlateauJDialog(null, true, produitsDuPlateau);
        newVoirPlateaux.setVisible(true);
    }//GEN-LAST:event_viewProduitJButton1ActionPerformed

    private void deleteProduitJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduitJButton1ActionPerformed
        DeleteProduitsPlateauJDialog1 deletePlateau = new DeleteProduitsPlateauJDialog1(null, true, iApp, this.produitsDuPlateau);
        this.produitsDuPlateau = deletePlateau.showDialog();
    }//GEN-LAST:event_deleteProduitJButton1ActionPerformed

    private void choosePlateauStandardCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePlateauStandardCommandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choosePlateauStandardCommandeActionPerformed

    private void nbPersonnesPlateauStandardJTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbPersonnesPlateauStandardJTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbPersonnesPlateauStandardJTextField3ActionPerformed

    private void quantitePlateauStandardJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitePlateauStandardJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitePlateauStandardJTextField4ActionPerformed

    private void nbPersonnesPlateauPersoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbPersonnesPlateauPersoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbPersonnesPlateauPersoJTextFieldActionPerformed

    private void quantitePlateauPersoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitePlateauPersoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitePlateauPersoJTextFieldActionPerformed

    private void enregistrerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerJButtonActionPerformed
        if(plateauxStandardsPersonnalisesButtonGroup.getSelection() == plateauxPersonnalisesJToggleButton.getModel()){
            try {
                if(!nbPersonnesPlateauPersoJTextField.getText().trim().isEmpty() && !quantitePlateauPersoJTextField.getText().trim().isEmpty()){
                    double prix = -1;
                    if(!prixUnitaireJTextField2.getText().isEmpty())
                        prix =  Double.parseDouble(prixUnitaireJTextField2.getText());
                    Plateau plateauAjoute = (Plateau) this.iApp.ajouterPlateauPerso(prix, nomPlateauJTextField2.getText(), produitsDuPlateau);
                    this.plateauDeLaCommandesObjs = new Object[]{plateauAjoute, nbPersonnesPlateauPersoJTextField.getText(), quantitePlateauPersoJTextField.getText()};
                }
                else
                    JOptionPane.showMessageDialog(this, "Veuillez entrer une quantité et un nombre de personnes", "Informations manquantes", JOptionPane.WARNING_MESSAGE);
            } catch (NomTropLongException ex) {
                JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            } catch (QuantiteParPersonneInvalideException ex) {
                JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            } catch (PrixInvalideException ex) {
                JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            } catch (ErreurInconnueException ex) {
                JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur inconnue", JOptionPane.ERROR_MESSAGE);
            }
        } else{
            if(!nbPersonnesPlateauStandardJTextField3.getText().trim().isEmpty() && !quantitePlateauStandardJTextField4.getText().trim().isEmpty()){
                this.plateauDeLaCommandesObjs = new Object[]{plateauxStandards.get(choosePlateauStandardCommande.getSelectedIndex()), nbPersonnesPlateauStandardJTextField3.getText(), quantitePlateauStandardJTextField4.getText()};
            }else
                JOptionPane.showMessageDialog(this, "Veuillez entrer une quantité et un nombre de personnes", "Informations manquantes", JOptionPane.WARNING_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_enregistrerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduitJButton1;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centreCommandesJPanel;
    private javax.swing.JComboBox<String> choosePlateauStandardCommande;
    private javax.swing.JLabel choosePlateauStandardCommandeJLabel;
    private javax.swing.JButton createFromPlateauStandard;
    private javax.swing.JPanel crudProduitPlateauPersoJPanel;
    private javax.swing.JButton deleteProduitJButton1;
    private javax.swing.JButton enregistrerJButton;
    private javax.swing.JPanel mainProduitsJPanel;
    private javax.swing.JLabel nbPersonnesPlateauPersoJLabel;
    private javax.swing.JTextField nbPersonnesPlateauPersoJTextField;
    private javax.swing.JLabel nbPersonnesPlateauStandardJLabel;
    private javax.swing.JTextField nbPersonnesPlateauStandardJTextField3;
    private javax.swing.JLabel nomPlateauJLabel2;
    private javax.swing.JTextField nomPlateauJTextField2;
    private javax.swing.JPanel plateauxPersonnalisesInformationJPanel;
    private javax.swing.JToggleButton plateauxPersonnalisesJToggleButton;
    private javax.swing.JToggleButton plateauxStandardJToggleButton;
    private javax.swing.JPanel plateauxStandardsInformationJPanel;
    private javax.swing.ButtonGroup plateauxStandardsPersonnalisesButtonGroup;
    private javax.swing.JLabel prixUnitaireJLabel2;
    private javax.swing.JTextField prixUnitaireJTextField2;
    private javax.swing.JLabel quantitePlateauPersoJLabel;
    private javax.swing.JTextField quantitePlateauPersoJTextField;
    private javax.swing.JLabel quantitePlateauStandardJLabel1;
    private javax.swing.JTextField quantitePlateauStandardJTextField4;
    private javax.swing.JButton viewProduitJButton1;
    // End of variables declaration//GEN-END:variables

}
