/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.IApp;
import Model.Commande.Commande;
import Model.Plateaux.Plateau;
import Model.Plateaux.PlateauPerso;
import Model.Produits.Produit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Timon Fournier
 */
public class DeletePlateauCommandeJDialog extends javax.swing.JDialog {

    private ArrayList<ArrayList> plateaux;
    private IApp iApp;

    /**
     * Crée un nouveau PlateauxJDialog depuis Commande->modifier
     */
    public DeletePlateauCommandeJDialog(java.awt.Frame parent, boolean modal, IApp iApp, Commande commande, ArrayList<ArrayList> plateau_quantite_nbpersonnesAAjouter) {
        super(parent, modal);
        this.iApp = iApp;

        this.plateaux = commande.getListePlateaux();
        for (ArrayList plateau : plateau_quantite_nbpersonnesAAjouter) {
            ArrayList element = new ArrayList();
            element.add((ArrayList) plateau.get(0));
            element.add((ArrayList) plateau.get(1));
            element.add((ArrayList) plateau.get(2));
            this.plateaux.add(element);
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * Crée un nouveau PlateauxJDialog depuis Commande->ajouter
     */
    public DeletePlateauCommandeJDialog(java.awt.Frame parent, boolean modal, IApp iApp, ArrayList<ArrayList> plateau_quantite_nbpersonnes) {
        super(parent, modal);
        this.iApp = iApp;

        this.plateaux = plateau_quantite_nbpersonnes;
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public ArrayList<ArrayList> showDialog() {
        this.setVisible(true);
        return this.plateaux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centrePlateauxJPanel1 = new javax.swing.JPanel();
        nomPlateauJLabel2 = new javax.swing.JLabel();
        choosePlateauToDeleteJComboBox2 = new javax.swing.JComboBox<Plateau>();
        mainPlateauxJPanel1 = new javax.swing.JPanel();
        creationPlateauJLabel1 = new javax.swing.JLabel();
        buttonRetourSaveJPanel1 = new javax.swing.JPanel();
        annulerJButton1 = new javax.swing.JButton();
        okJButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        centrePlateauxJPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centrePlateauxJPanel1.setLayout(new java.awt.GridBagLayout());

        nomPlateauJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomPlateauJLabel2.setText("Choisisez le plateau à supprimer :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        centrePlateauxJPanel1.add(nomPlateauJLabel2, gridBagConstraints);

        DefaultComboBoxModel deletePlateauCBBModel = new DefaultComboBoxModel<Plateau>();
        for (Object element : plateaux){
            deletePlateauCBBModel.addElement(element);
        }
        choosePlateauToDeleteJComboBox2.setModel(deletePlateauCBBModel);
        centrePlateauxJPanel1.add(choosePlateauToDeleteJComboBox2, new java.awt.GridBagConstraints());

        getContentPane().add(centrePlateauxJPanel1, java.awt.BorderLayout.CENTER);

        creationPlateauJLabel1.setText("Suppression des plateaux standards");
        mainPlateauxJPanel1.add(creationPlateauJLabel1);

        getContentPane().add(mainPlateauxJPanel1, java.awt.BorderLayout.PAGE_START);

        annulerJButton1.setText("Annuler");
        annulerJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButton1ActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel1.add(annulerJButton1);

        okJButton1.setText("OK");
        okJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButton1ActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel1.add(okJButton1);

        getContentPane().add(buttonRetourSaveJPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButton1ActionPerformed
        ArrayList plateau_quantite_nbpersonnes = (ArrayList) this.choosePlateauToDeleteJComboBox2.getSelectedItem();
        Plateau plateauSelectionne;
        if (plateau_quantite_nbpersonnes != null) {
            plateauSelectionne = (Plateau) plateau_quantite_nbpersonnes.get(0);
            int indice = this.choosePlateauToDeleteJComboBox2.getSelectedIndex();
            if (plateauSelectionne.getClass() == PlateauPerso.class) {
                iApp.supprimer(plateauSelectionne);
            }
            int result = JOptionPane.showConfirmDialog(rootPane, "Etes-vous sûr de vouloir supprimer " + plateauSelectionne, "Confirmez", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                this.plateaux.remove(indice);
            }
        }
        this.dispose();
    }//GEN-LAST:event_okJButton1ActionPerformed

    private void annulerJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerJButton1;
    private javax.swing.JPanel buttonRetourSaveJPanel1;
    private javax.swing.JPanel centrePlateauxJPanel1;
    private javax.swing.JComboBox<Plateau> choosePlateauToDeleteJComboBox2;
    private javax.swing.JLabel creationPlateauJLabel1;
    private javax.swing.JPanel mainPlateauxJPanel1;
    private javax.swing.JLabel nomPlateauJLabel2;
    private javax.swing.JButton okJButton1;
    // End of variables declaration//GEN-END:variables
}
