/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.IApp;
import Model.Plateaux.*;
import Model.Produits.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Léa Berne
 */
public class DeleteProduitsPlateauJDialog1 extends javax.swing.JDialog {

    private ArrayList<Produit> produitsDuPlateau;
    private IApp iApp;

    /**
     * Creates new form PlateauxJDialog
     */
    public DeleteProduitsPlateauJDialog1(java.awt.Frame parent, boolean modal, IApp iApp, Plateau plateau, ArrayList<Produit> produitsAAjouter) {
        super(parent, modal);
        this.iApp = iApp;
        this.produitsDuPlateau = plateau.getListeProduits();
        for(Produit produit : produitsAAjouter)    
            this.produitsDuPlateau.add(produit);
        initComponents();
    }
    
    public DeleteProduitsPlateauJDialog1(java.awt.Frame parent, boolean modal, IApp iApp, ArrayList<Produit> produitsDuPlateau) {
        super(parent, modal);
        this.iApp = iApp;
        this.produitsDuPlateau = produitsDuPlateau;
        initComponents();
    }
    
    public ArrayList<Produit> showDialog(){
        this.setVisible(true);
        return produitsDuPlateau;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPlateauxJPanel = new javax.swing.JPanel();
        deleteProduitPlateauJLabel = new javax.swing.JLabel();
        centrePlateauxJPanel = new javax.swing.JPanel();
        produitsPlateauJComboBox = new javax.swing.JComboBox<Produit>();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        okJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        deleteProduitPlateauJLabel.setText("Supprimer un produit du plateau standard");
        mainPlateauxJPanel.add(deleteProduitPlateauJLabel);

        getContentPane().add(mainPlateauxJPanel, java.awt.BorderLayout.PAGE_START);

        centrePlateauxJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centrePlateauxJPanel.setLayout(new java.awt.GridBagLayout());

        DefaultComboBoxModel viewProduitsCBBModel = new DefaultComboBoxModel<Produit>();
        for (Produit produit : produitsDuPlateau){
            viewProduitsCBBModel.addElement((Produit)produit);
        }
        produitsPlateauJComboBox.setModel(viewProduitsCBBModel);
        produitsPlateauJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsPlateauJComboBoxActionPerformed(evt);
            }
        });
        centrePlateauxJPanel.add(produitsPlateauJComboBox, new java.awt.GridBagConstraints());

        getContentPane().add(centrePlateauxJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(okJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        Produit produitSelectionne = (Produit) this.produitsPlateauJComboBox.getSelectedItem();
        int result = JOptionPane.showConfirmDialog(rootPane, "Etes-vous sûr de vouloir supprimer " + produitSelectionne.getNom(), "Confirmez", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            //TODO : try catch
            this.dispose();
        }
    }//GEN-LAST:event_okJButtonActionPerformed

    private void produitsPlateauJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitsPlateauJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produitsPlateauJComboBoxActionPerformed

    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centrePlateauxJPanel;
    private javax.swing.JLabel deleteProduitPlateauJLabel;
    private javax.swing.JPanel mainPlateauxJPanel;
    private javax.swing.JButton okJButton;
    private javax.swing.JComboBox<Produit> produitsPlateauJComboBox;
    // End of variables declaration//GEN-END:variables
}
