/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.IApp;
import Model.Commande.*;
import Model.Plateaux.Plateau;
import java.awt.CardLayout;
import javax.swing.JToggleButton;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Léa Berne
 */
public class EditCommandeJDialog extends javax.swing.JDialog {
    private Commande commande;
    private Object[] commandesObjs;
    private IApp iApp;
    private ArrayList<ArrayList> idQuantiteNbpersonnesPlateaux;

    /**
     * Creates new form CommandesJDialog
     */
    public EditCommandeJDialog(java.awt.Frame parent, boolean modal, IApp iApp, Commande commande) {
        super(parent, modal);
        this.iApp = iApp;
        this.commande = commande; 
        initComponents();
        idQuantiteNbpersonnesPlateaux = new ArrayList<ArrayList>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plateauxStandardsPersonnalisesButtonGroup = new javax.swing.ButtonGroup();
        mainProduitsJPanel = new javax.swing.JPanel();
        editCommandeJLabel = new javax.swing.JLabel();
        editPlateauJPanel = new javax.swing.JPanel();
        infoJPanel = new javax.swing.JPanel();
        nomClientJLabel = new javax.swing.JLabel();
        nomClientJTextField = new javax.swing.JTextField();
        dateRecuperationJLabel = new javax.swing.JLabel();
        Date date = Date.from(this.commande.getDateRecuperation().atStartOfDay(ZoneId.systemDefault()).toInstant());
        dateRecuperationJDateChooser = new com.toedter.calendar.JDateChooser(date);
        prixJLabel = new javax.swing.JLabel();
        prixJTextField = new javax.swing.JTextField();
        montantPayeJLabel = new javax.swing.JLabel();
        montantPayeJTextField = new javax.swing.JTextField();
        commentJPanel = new javax.swing.JPanel();
        commentairesJLabel1 = new javax.swing.JLabel();
        commentairesJScrollPane1 = new javax.swing.JScrollPane();
        commentairesJTextArea1 = new javax.swing.JTextArea();
        crudJPanel = new javax.swing.JPanel();
        deletePlateauJButton = new javax.swing.JButton();
        viewPlateauxCommandeJButton = new javax.swing.JButton();
        addPlateauCommandejButton1 = new javax.swing.JButton();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        enregistrerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        editCommandeJLabel.setText("Edition d'une commande");
        mainProduitsJPanel.add(editCommandeJLabel);

        getContentPane().add(mainProduitsJPanel, java.awt.BorderLayout.NORTH);

        editPlateauJPanel.setLayout(new java.awt.BorderLayout(0, 10));

        infoJPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        nomClientJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomClientJLabel.setText("Nom du client");
        infoJPanel.add(nomClientJLabel);

        nomClientJTextField.setText(this.commande.getNomClient());
        nomClientJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoJPanel.add(nomClientJTextField);

        dateRecuperationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateRecuperationJLabel.setText("Date de récupération");
        infoJPanel.add(dateRecuperationJLabel);
        infoJPanel.add(dateRecuperationJDateChooser);

        prixJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixJLabel.setText("Prix");
        infoJPanel.add(prixJLabel);

        prixJTextField.setText(this.commande.getPrix()+"");
        prixJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoJPanel.add(prixJTextField);

        montantPayeJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        montantPayeJLabel.setText("Montant payé");
        infoJPanel.add(montantPayeJLabel);

        montantPayeJTextField.setText(this.commande.getMontantPaye()+"");
        montantPayeJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        infoJPanel.add(montantPayeJTextField);

        editPlateauJPanel.add(infoJPanel, java.awt.BorderLayout.NORTH);

        commentairesJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commentairesJLabel1.setText("Commentaires");
        commentJPanel.add(commentairesJLabel1);

        commentairesJTextArea1.setText(this.commande.getCommentaires());
        commentairesJTextArea1.setColumns(20);
        commentairesJTextArea1.setRows(5);
        commentairesJScrollPane1.setViewportView(commentairesJTextArea1);

        commentJPanel.add(commentairesJScrollPane1);

        editPlateauJPanel.add(commentJPanel, java.awt.BorderLayout.CENTER);

        crudJPanel.setLayout(new java.awt.GridLayout(1, 0));

        deletePlateauJButton.setText("Supprimer un plateau");
        deletePlateauJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlateauJButtonActionPerformed(evt);
            }
        });
        crudJPanel.add(deletePlateauJButton);

        viewPlateauxCommandeJButton.setText("Voir les plateaux");
        viewPlateauxCommandeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPlateauxCommandeJButtonActionPerformed(evt);
            }
        });
        crudJPanel.add(viewPlateauxCommandeJButton);

        addPlateauCommandejButton1.setText("Ajouter un plateau");
        addPlateauCommandejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlateauCommandejButton1ActionPerformed(evt);
            }
        });
        crudJPanel.add(addPlateauCommandejButton1);

        editPlateauJPanel.add(crudJPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(editPlateauJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        enregistrerJButton.setText("Enregistrer");
        enregistrerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(enregistrerJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Object[] showDialog(){
        this.setVisible(true);
        return commandesObjs;
    }
    
    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed

    private void addPlateauCommandejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlateauCommandejButton1ActionPerformed
        AjoutPlateauCommandeJDialog newCommandesJDialog = new AjoutPlateauCommandeJDialog(null, true,  iApp);
        Object[] plateaux = newCommandesJDialog.showDialog();//type, plateau, nbPersonnes, quantite
        if(plateaux != null) {
            ArrayList idQuantiteNbpersonnes = new ArrayList();
            idQuantiteNbpersonnes.add((Plateau)plateaux[0]);
            idQuantiteNbpersonnes.add(Integer.parseInt((String) plateaux[1]));
            idQuantiteNbpersonnes.add(Integer.parseInt((String) plateaux[2]));
            idQuantiteNbpersonnesPlateaux.add(idQuantiteNbpersonnes);
        }
    }//GEN-LAST:event_addPlateauCommandejButton1ActionPerformed

    private void deletePlateauJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlateauJButtonActionPerformed
        DeletePlateauCommandeJDialog deletePlateau = new DeletePlateauCommandeJDialog((App) this.getOwner(), true, this.iApp,this.commande, this.idQuantiteNbpersonnesPlateaux);
        deletePlateau.setVisible(true);
    }//GEN-LAST:event_deletePlateauJButtonActionPerformed

    private void enregistrerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerJButtonActionPerformed
        try{
            this.commandesObjs = new Object[]{nomClientJTextField.getText(), dateRecuperationJDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), prixJTextField.getText(), montantPayeJTextField.getText(), commentairesJTextArea1.getText(), this.idQuantiteNbpersonnesPlateaux};
            App owner = (App) this.getOwner();
            owner.refreshTableCommande();
            this.dispose();
            
        } catch(java.lang.NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir une date de récupération", "Information manquante", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_enregistrerJButtonActionPerformed

    private void viewPlateauxCommandeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPlateauxCommandeJButtonActionPerformed
        ViewPlateauxCommandeJDialog newVoirPlateaux = new ViewPlateauxCommandeJDialog(null, true, idQuantiteNbpersonnesPlateaux);
        newVoirPlateaux.setVisible(true);
    }//GEN-LAST:event_viewPlateauxCommandeJButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlateauCommandejButton1;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel commentJPanel;
    private javax.swing.JLabel commentairesJLabel1;
    private javax.swing.JScrollPane commentairesJScrollPane1;
    private javax.swing.JTextArea commentairesJTextArea1;
    private javax.swing.JPanel crudJPanel;
    private com.toedter.calendar.JDateChooser dateRecuperationJDateChooser;
    private javax.swing.JLabel dateRecuperationJLabel;
    private javax.swing.JButton deletePlateauJButton;
    private javax.swing.JLabel editCommandeJLabel;
    private javax.swing.JPanel editPlateauJPanel;
    private javax.swing.JButton enregistrerJButton;
    private javax.swing.JPanel infoJPanel;
    private javax.swing.JPanel mainProduitsJPanel;
    private javax.swing.JLabel montantPayeJLabel;
    private javax.swing.JTextField montantPayeJTextField;
    private javax.swing.JLabel nomClientJLabel;
    private javax.swing.JTextField nomClientJTextField;
    private javax.swing.ButtonGroup plateauxStandardsPersonnalisesButtonGroup;
    private javax.swing.JLabel prixJLabel;
    private javax.swing.JTextField prixJTextField;
    private javax.swing.JButton viewPlateauxCommandeJButton;
    // End of variables declaration//GEN-END:variables
}
