/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.Exceptions.ErreurInconnueException;
import Controller.Exceptions.NomTropLongException;
import Controller.Exceptions.PrixInvalideException;
import Controller.Exceptions.QuantiteParPersonneInvalideException;
import Controller.IApp;
import Model.Plateaux.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author potatos
 */
public class EditPlateauJDialog extends javax.swing.JDialog {

    private PlateauStandard plateau;
    private ArrayList produitsAAjouter = new ArrayList();
    private ArrayList produitsASupprimer = new ArrayList();

    private IApp iApp;

    /**
     * Creates new form PlateauxJDialog
     */
    public EditPlateauJDialog(java.awt.Frame parent, boolean modal, IApp iApp, PlateauStandard plateau) {
        super(parent, modal);
        this.plateau = plateau;
        this.iApp = iApp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPlateauxJPanel = new javax.swing.JPanel();
        creationPlateauJLabel = new javax.swing.JLabel();
        centrePlateauxJPanel = new javax.swing.JPanel();
        prixUnitaireJLabel1 = new javax.swing.JLabel();
        prixUnitaireJTextField1 = new javax.swing.JTextField(this.plateau.getPrix()+"");
        nomPlateauJLabel1 = new javax.swing.JLabel();
        nomPlateauJTextField1 = new javax.swing.JTextField(this.plateau.getNomPlateau());
        jPanel2 = new javax.swing.JPanel();
        deleteProduitJButton = new javax.swing.JButton();
        viewProduitJButton = new javax.swing.JButton();
        addProduitJButton = new javax.swing.JButton();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        annulerJButton = new javax.swing.JButton();
        enregistrerJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        creationPlateauJLabel.setText("Edition d'un plateau standard");
        mainPlateauxJPanel.add(creationPlateauJLabel);

        getContentPane().add(mainPlateauxJPanel, java.awt.BorderLayout.PAGE_START);

        centrePlateauxJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centrePlateauxJPanel.setLayout(new java.awt.GridBagLayout());

        prixUnitaireJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixUnitaireJLabel1.setText("Prix unitaire ( Euro / Personne )");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        centrePlateauxJPanel.add(prixUnitaireJLabel1, gridBagConstraints);

        prixUnitaireJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixUnitaireJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixUnitaireJTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        centrePlateauxJPanel.add(prixUnitaireJTextField1, gridBagConstraints);

        nomPlateauJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomPlateauJLabel1.setText("Nom du plateau");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        centrePlateauxJPanel.add(nomPlateauJLabel1, gridBagConstraints);

        nomPlateauJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomPlateauJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomPlateauJTextField1ActionPerformed(evt);
            }
        });
        nomPlateauJTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nomPlateauJTextField1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        centrePlateauxJPanel.add(nomPlateauJTextField1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        deleteProduitJButton.setText("Supprimer un produit");
        deleteProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteProduitJButton);

        viewProduitJButton.setText("Voir les produits");
        viewProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewProduitJButton);

        addProduitJButton.setText("Ajouter un produit");
        addProduitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProduitJButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addProduitJButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        centrePlateauxJPanel.add(jPanel2, gridBagConstraints);

        getContentPane().add(centrePlateauxJPanel, java.awt.BorderLayout.CENTER);

        annulerJButton.setText("Annuler");
        annulerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(annulerJButton);

        enregistrerJButton.setText("Enregistrer");
        enregistrerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(enregistrerJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annulerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerJButtonActionPerformed

    private void addProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProduitJButtonActionPerformed
        // TODO add your handling code here:
        AjoutProduitsPlateauxJDialog ajoutProduits = new AjoutProduitsPlateauxJDialog((App) this.getOwner(), true, this.iApp);
        ajoutProduits.setVisible(true);
    }//GEN-LAST:event_addProduitJButtonActionPerformed

    private void viewProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProduitJButtonActionPerformed
        ViewProduitsPlateauJDialog ajoutProduits = new ViewProduitsPlateauJDialog((App) this.getOwner(), true, this.plateau, this.produitsAAjouter);
        ajoutProduits.setVisible(true);
    }//GEN-LAST:event_viewProduitJButtonActionPerformed

    private void deleteProduitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduitJButtonActionPerformed
       DeleteProduitsPlateauJDialog1 ajoutProduits = new DeleteProduitsPlateauJDialog1((App) this.getOwner(), true, iApp, this.plateau, this.produitsAAjouter);
        ajoutProduits.setVisible(true);
    }//GEN-LAST:event_deleteProduitJButtonActionPerformed

    private void nomPlateauJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomPlateauJTextField1ActionPerformed

    }//GEN-LAST:event_nomPlateauJTextField1ActionPerformed

    private void prixUnitaireJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixUnitaireJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixUnitaireJTextField1ActionPerformed

    private void enregistrerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerJButtonActionPerformed
        String textPrix = this.prixUnitaireJTextField1.getText();
        double prix = Double.parseDouble(textPrix);
        String nom = this.nomPlateauJTextField1.getText();
        try {
            iApp.modifierPlateauStandard(this.plateau, prix, nom, this.produitsAAjouter);
        } catch (NomTropLongException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (QuantiteParPersonneInvalideException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (PrixInvalideException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (ErreurInconnueException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        App owner = (App) this.getOwner();
        owner.refreshTablePlateaux();
    }//GEN-LAST:event_enregistrerJButtonActionPerformed

    private void nomPlateauJTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nomPlateauJTextField1PropertyChange

    }//GEN-LAST:event_nomPlateauJTextField1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduitJButton;
    private javax.swing.JButton annulerJButton;
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centrePlateauxJPanel;
    private javax.swing.JLabel creationPlateauJLabel;
    private javax.swing.JButton deleteProduitJButton;
    private javax.swing.JButton enregistrerJButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPlateauxJPanel;
    private javax.swing.JLabel nomPlateauJLabel1;
    private javax.swing.JTextField nomPlateauJTextField1;
    private javax.swing.JLabel prixUnitaireJLabel1;
    private javax.swing.JTextField prixUnitaireJTextField1;
    private javax.swing.JButton viewProduitJButton;
    // End of variables declaration//GEN-END:variables
}
