/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View2;

import Controller.IApp;
import Model.Plateaux.*;
import Model.Produits.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Léa Berne
 */
public class ViewProduitsPlateauJDialog extends javax.swing.JDialog {
    private ArrayList produitsDuPlateau;
    /**
     * Creates new form PlateauxJDialog
     */
    public ViewProduitsPlateauJDialog(java.awt.Frame parent, boolean modal, PlateauStandard plateau, ArrayList produitsAAjouter) {
        super(parent, modal);
        this.produitsDuPlateau = produitsAAjouter;
        this.produitsDuPlateau.add(plateau);
        initComponents();
    }
    
    public ViewProduitsPlateauJDialog(java.awt.Frame parent, boolean modal, ArrayList produitsDuPlateau) {
        super(parent, modal);
        this.produitsDuPlateau = produitsDuPlateau;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPlateauxJPanel = new javax.swing.JPanel();
        creationPlateauJLabel = new javax.swing.JLabel();
        centrePlateauxJPanel = new javax.swing.JPanel();
        produitsPlateauJComboBox = new javax.swing.JComboBox<Produit>();
        buttonRetourSaveJPanel = new javax.swing.JPanel();
        okJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        creationPlateauJLabel.setText("Voir les produits du plateau standard");
        mainPlateauxJPanel.add(creationPlateauJLabel);

        getContentPane().add(mainPlateauxJPanel, java.awt.BorderLayout.PAGE_START);

        centrePlateauxJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        centrePlateauxJPanel.setLayout(new java.awt.GridBagLayout());

        DefaultComboBoxModel viewProduitsCBBModel = new DefaultComboBoxModel<Produit>();

        for (Object produit : this.produitsDuPlateau){
            viewProduitsCBBModel.addElement(produit);
        }
        produitsPlateauJComboBox.setModel(viewProduitsCBBModel);
        produitsPlateauJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produitsPlateauJComboBoxActionPerformed(evt);
            }
        });
        centrePlateauxJPanel.add(produitsPlateauJComboBox, new java.awt.GridBagConstraints());

        getContentPane().add(centrePlateauxJPanel, java.awt.BorderLayout.CENTER);

        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        buttonRetourSaveJPanel.add(okJButton);

        getContentPane().add(buttonRetourSaveJPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okJButtonActionPerformed

    private void produitsPlateauJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produitsPlateauJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produitsPlateauJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonRetourSaveJPanel;
    private javax.swing.JPanel centrePlateauxJPanel;
    private javax.swing.JLabel creationPlateauJLabel;
    private javax.swing.JPanel mainPlateauxJPanel;
    private javax.swing.JButton okJButton;
    private javax.swing.JComboBox<Produit> produitsPlateauJComboBox;
    // End of variables declaration//GEN-END:variables
}
